# Generated by Django 4.2.7 on 2024-01-28 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrapbox', '0015_remove_cartitem_cart_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapbox',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
