# Generated by Django 4.2.7 on 2024-02-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbox', '0019_alter_wishlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapbox',
            name='owner',
        ),
    ]
